main: com.billehbawb.punishgui.PunishGUI
version: ${project.version}
name: PunishGUI
commands:
  punish:
    description: Used to punish dirty rule breakers.
    aliases: punishgui
    permission: "punishgui.use"